### ISSUE TITLE
Set up C++ framework for making API calls

### ISSUE THREAD

**Issue by Bocklavich** [EECE3093C/team-project-green-software#6] opened 2023-03-03 16:41 UTC

**Comment by jack-margeson** [comment] 2023-03-21 17:21
This ticket includes:

- Finding the best way to download/access data from the plant API. 
     - Accessing the API online or downloading dataset from JSON and querying on-site?
- Pulling a plant (test) information from the API and displaying it to the user

This ticket does not include:
- Creating a search system for plants that are available in the API--see #17

**Comment by jack-margeson** [comment] 2023-03-21 17:31
Closing as a duplicate of #16--will re-assign you to the new issue @Bocklavich.

**Closed by jack-margeson** 2023-03-21 17:31 UTC
Labels: feature
